@echo off 
echo ImageMagick fix libpng warning: iCCP: Not recognizing known sRGB profile ...... 
echo Search PNG in subdirs and process ... 
set fn=C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\magick.exe convert 
for /f "tokens=*" %%i in ('dir/s/b *.png') do "%fn%" "%%i" -strip "%%i" 
pause
